create table public.engineer_news (
    news_id bigint generated by default as identity primary key,
    news_title varchar(255) not null,
    category varchar(50) not null,
    published_date timestamptz not null default now(),
    news_image text,
    priority integer not null default 0,
    news_content text not null,
    created_at timestamptz not null default now()
);

alter table public.engineer_news enable row level security;